vacation_location = [ 'Ice Island', 'Hawayi', 'Paris', 'Yajiada', 'sydiny']
print(vacation_location)
print(sorted(vacation_location))
print(vacation_location)
print(sorted(vacation_location,reverse = True))
print(vacation_location)
vacation_location.reverse()
print(vacation_location)
vacation_location.reverse()
print(vacation_location)
vacation_location.sort()
print(vacation_location)
vacation_location.sort(reverse=True)
print(vacation_location)
